service: airly-history

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment:
    AIRLY_API_BASE_URL: https://airapi.airly.eu/v2
    AIRLY_API_KEY: ${ssm:/aws/reference/secretsmanager/dev/AirlyApiKey~true}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    LOCATION_SEARCH_LAT: '50.019752'
    LOCATION_SEARCH_LNG: '19.979046'
    LOCATION_SEARCH_RADIUS: 100
    LOCATION_SEARCH_LIMIT: 50
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  fetchAirQualityData:
    handler: handler.fetchAirQualityData
    events:
      - schedule: cron(0 0 * * ? *)

resources:
  Resources:
    AirQualityDataDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
